### ISSUE TITLE
HTTP400 when trying to create PR

### ISSUE THREAD

**Issue by lukaszett** [mburumaxwell/paklo#2069]
### Categorization

- [x] This is not a permissions issue (Seek help at https://github.com/mburumaxwell/dependabot-azure-devops/discussions/1245)
- [x] This is an issue specific to Azure DevOps or this repository and does not belong in [dependabot-core](https://github.com/dependabot/dependabot-core).
Specific issues for dependabot are solved faster in the core repository. For example, why a package version is skipped.
Trying out this behaviour in the GitHub Hosted version can help you pinpoint where it lies.

- [x] I have linked a public reproduction of the specific issue or none is required because the issue is not specific to me.
Please note that you can create a public organization/project and repository to show the issue. This tends to accelerate resolution.

### Steps to reproduce

When running the dependabot task in my repo everything seems to work fine up until the PR is about to be created.

However, the API calls fails with 400 Bad Request and no PR is created.

### Expected behavior

A PR for the new versions is created.

### Logs and screenshots

`[06:27:12.814] INFO: Processing 'create_pull_request' for job ID '1369470283'
[06:27:12.866] INFO: Creating pull request 'Bump schwifty from 2025.7.0 to 2025.9.0'...
[06:27:12.866] INFO:  - Pushing 3 file change(s) to branch 'dependabot/uv/dev/schwifty-2025.9.0'...
[06:27:13.042] ERROR: Failed to create pull request: Error: HTTP POST 'https://dev.azure.com/XXXXXXXXXXXXXX/_apis/git/repositories/XXXXXXXX/pushes?api-version=5.0' failed: 400 Bad Request
  proxy | 2025/10/17 06:27:13 [578] 400 http://host.docker.internal:33925/api/update_jobs/1369470283/create_pull_request
[06:27:13.042] DEBUG: HTTP POST 'https://dev.azure.com/XXXXXXXXXXXXXXXXX/XXXXXXXXXXXX/_apis/git/repositories/xxxxxxxxxxxxxxxxx/pushes?api-version=5.0' failed: 400 Bad Request
    err: {
      "type": "HttpRequestError",
      "message": "HTTP POST 'https://dev.azure.com/XXXXXXXXXXXXXXXXX/XXXXXXXXXXXX/_apis/git/repositories/xxxxxxxxxxxxxxxxx/pushes?api-version=5.0' failed: 400 Bad Request",
      "stack":
          Error: HTTP POST 'https://dev.azure.com/XXXXXXXXXXXXXXXXX/XXXXXXXXXXXX/_apis/git/repositories/xxxxxxxxxxxxxxxxx/pushes?api-version=5.0' failed: 400 Bad Request
              at sendRestApiRequestWithRetry (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/packages/paklo/dist/azure-DMMAAyIe.js:604:1)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at AzureDevOpsWebApiClient.restApiPost (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/packages/paklo/dist/azure-DMMAAyIe.js:546:1)
              at AzureDevOpsWebApiClient.createPullRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/packages/paklo/dist/azure-DMMAAyIe.js:329:1)
              at AzureLocalDependabotServer.handle (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/packages/paklo/dist/azure-DMMAAyIe.js:732:1)
              at /home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/packages/paklo/dist/dependabot-BMDNSxJV.js:1912:1
              at dispatch (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/node_modules/hono/dist/compose.js:22:1)
              at /home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/node_modules/hono/dist/validator/validator.js:81:1
              at dispatch (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/node_modules/hono/dist/compose.js:22:1)
              at app.on.object.data (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/packages/paklo/dist/dependabot-BMDNSxJV.js:1908:1)
      "code": 400
    }
`

### Extension Host

Azure Dev Ops

### Extension Version

2.59.1.0

### Additional context

This is my dependabot.yaml:

```
version: 2

updates:
- package-ecosystem: "uv"
  directory: "/"
```

This is my pipeline code:
```
trigger: none # Disable CI trigger

schedules:
- cron: '0 5 * * *'
  always: true # run even when there are no code changes
  branches:
    include:
      - prod
      - dev
  batch: true
  displayName: Daily

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: dependabot@2
  inputs:
    mergeStrategy: 'squash'
    azureDevOpsAccessToken: '$(TOKEN)'
```

**Comment by mburumaxwell** [comment]
Thanks @kaiwenleee for the detail. Fixed this in c327af125436d5eb2afb0df7d4f24f53beac60d9, released [here](https://github.com/mburumaxwell/dependabot-azure-devops/releases/tag/extension-azure-devops%402.59.10). Do let me know if resolved.

**Comment by mburumaxwell** [comment]
@kaiwenleee 
Thanks for the repro. I am not any good with go besides saying the English word but I was able to reproduce the issue. Turns out, #2215 introduced a bug when changing from string to enum for `content_encoding`. In practice it can be an empty string (not sure why). This should be fixed in #2243
Repro: https://dev.azure.com/tingle/dependabot/_git/repro-2069

However, with #2215, we did fix the original issue, which I believe was about removing an existing file.
Repro: https://dev.azure.com/tingle/dependabot/_git/repro-2069/pullrequest/31241?_a=files&path=/vendor/.DS_Store
This would technically make https://github.com/dependabot/dependabot-core/pull/13595 unnecessary.

There is a new extension version [extension-azure-devops@2.59.13](https://github.com/mburumaxwell/dependabot-azure-devops/releases/tag/extension-azure-devops%402.59.13)

Hopefully, you can report back once you test.

**Comment by lukaszett** [comment]
I just ran my pipeline using the new version, and I can confirm that the issue persists exactly as described in the original post. Thank you for you help so far!

**Comment by kaiwenleee** [comment]
just a thought, but could it be that `VersionControlChangeType.Rename` needs some special handling?

**Comment by kaiwenleee** [comment]
I see in your repro the k8s.io dependencies are not actually added, so they are skipped in pipeline. Can you try to include this commit? thank you 
https://github.com/kaiwenleee/update-go-mod/commit/a6bee850798872bc06c6def40fd96e36ec5c9a9e

**Comment by mburumaxwell** [comment]
@lukaszett unfortunately, I am unable to help without a reproduction. Perhaps you could open a new issue when you can make one, just like @kaiwenleee did?

@kaiwenleee , I have managed to reproduce the issue: https://dev.azure.com/tingle/dependabot/_build/results?buildId=74284&view=results. Sifting through the logs, there was not much information (will need to to improve it) but one running locally, I noticed the payload for one particular update (`kubernetes/client-go`) is quite big. Once again, this hits a limit for Azure DevOps that I wasn't already aware of. The response body:
```json
{
    "$id": "1",
    "innerException": null,
    "message": "The maximum request size of 26214400 bytes was exceeded.\r\nParameter name: contentStream",
    "typeName": "Microsoft.TeamFoundation.SourceControl.WebServer.InvalidArgumentValueException, Microsoft.TeamFoundation.SourceControl.WebServer",
    "typeKey": "InvalidArgumentValueException",
    "errorCode": 0,
    "eventId": 0
}
```
26214400 bytes is 25MiB which is quite significant. It happens for the push (i.e. commits) before the creation of the pull request (it will be evident in recent logs with the new client). The other deps are still updated.
Reading:
- https://community.powerplatform.com/forums/thread/details/?threadid=c436c391-b2d2-ef11-8eea-7c1e521423c2
- https://developercommunity.visualstudio.com/t/maximum-request-size-exceeded-when-check/10675100?sort=newest
- https://stackoverflow.com/questions/66004311/not-able-to-push-to-git-repository-programmatically-if-the-file-size-is-more-tha

I did try to increase the limit as per the last recommendation but doesn't seem to work. Perhaps you could give that a try?
Otherwise, I'd recommend doing manual updates for this dependency and adding an ignore entry in the config.

**Comment by kaiwenleee** [comment]
@mburumaxwell Thank you so much for debugging this! 

Indeed it makes sense that we hit a size limit from Azure DevOps. I think the size limit is probably on the HTTP request body, not just one single file. That's probably why increasing that limit didn't work for you - we didn't enable that limit at all. And PR is successfully created when we do a smaller update on `kubernetes/client-go`.

So it's not an issue with the extension and it works perfect for us right now. We know what's the issue and can update big dependencies manually. Thank you so much for your help!
